version: "3.8"

services:
  website:
    image: php:apache
    container_name: website
    environment:
      USERNAME: "toto"
      PASSWORD: "python"
    volumes:
      - ./website:/var/www/html
    depends_on:
      - api
    ports:
      - "86:80"
    networks:
      - student_network

  api:
    image: student_age_api
    container_name: api
    volumes:
      - ./simple_api/:/data/
    ports:
      - "5000:5000"
    networks:
      - student_network
networks:
  student_network:
    driver: bridge
