version: "3.8"

services:
  registry:
    image: registry:2.8.1
    container_name: registry
    ports:
      - "5005:5000"
    # volumes:
    #  - ./simple_api/config.yml:/etc/docker/registry/config.yml 
    networks:
      - registry_network

  registry_ui:
    image: joxit/docker-registry-ui:2
    container_name: registry_frontend
    ports:
      - "8082:80"
    environment:
      - REGISTRY_URL=http://registry:5005
      - REGISTRY_TITLE=Pozos
      - DELETE_IMAGE=true
    networks:
      - registry_network

networks:
  registry_network:
    driver: bridge
