version: "3.8"

services:
  registry:
    image: registry:2.8.1
    container_name: registry
    ports:
      - "5005:5000"
    # volumes:
    #  - ./simple_api/config.yml:/etc/docker/registry/config.yml 
    networks:
      - registry_network

  registry_ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry_frontend
    ports:
      - "8085:80"
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5005
      - REGISTRY_URL=http://registry:5005
      - REGISTRY_TITLE=Nanotech
    networks:
      - registry_network

networks:
  registry_network:
    driver: bridge
